name: uol_open
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  webview_flutter: 0.2.0
  carousel_pro: 1.0.0
  intl: 0.15.8
  html: 0.14.0+2
  http: 0.12.0+2
  location: 2.3.5
  provider: 3.0.0
  flutter_map: 0.7.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - lib/assets/images/inb.jpg
    - lib/assets/images/cathedral.jpg
    - lib/assets/images/cathedral2.jpg
    - lib/assets/images/uniLogoPortrait.jpg
    - lib/assets/images/gcw1.jpg
    - lib/assets/images/gcw2.jpg
    - lib/assets/images/gcw3.jpg
    - lib/assets/images/gcw4.jpg
    - lib/assets/images/gcw5.jpg
    - lib/assets/images/uniLogoLandscapeWhite.jpg
    - lib/assets/images/su-logo-white.png
    - lib/assets/images/barge1.jpg
    - lib/assets/images/barge2.jpg
    - lib/assets/images/barge3.jpg
    - lib/assets/images/swan1.jpg
    - lib/assets/images/swan2.jpg
    - lib/assets/images/swan3.jpg
    - lib/assets/images/shed1.jpg
    - lib/assets/images/shed2.jpg
    - lib/assets/images/towerbar1.jpg
    - lib/assets/images/towerbar2.jpg
    - lib/assets/images/towerbar3.jpg
    - lib/assets/images/potw1.jpg
    - lib/assets/images/potw2.jpg
    - lib/assets/images/potw3.jpg
    - lib/assets/images/potw4.jpg
    - lib/assets/images/potw5.jpg
    - lib/assets/images/potw6.jpg
    - lib/assets/images/aboutuni1.jpg
    - lib/assets/images/aboutuni2.jpg
    - lib/assets/images/aboutuni3.jpg
    - lib/assets/images/courts1.jpg
    - lib/assets/images/courts2.jpg
    - lib/assets/images/courts3.jpg
    - lib/assets/images/cygnet1.jpg
    - lib/assets/images/cygnet2.jpg
    - lib/assets/images/cygnet3.jpg
  fonts:
    - family: GoudyModern
      fonts:
        - asset: lib/assets/fonts/Goudy-Modern-MT-Std-Regular.otf
    - family: Helvetica
      fonts:
        - asset: lib/assets/fonts/Helvetica.ttf
        - asset: lib/assets/fonts/Helvetica-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Helvetica-Oblique.ttf
          style: italic
        - asset: lib/assets/fonts/Helvetica-BoldOblique.ttf
          weight: 700
          style: italic
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
